### ISSUE TITLE
pierwsza funkcjonalność

### ISSUE THREAD

**Issue by yyarp** [yyarp/WeedMoister#1]
polega na generowaniu tablic z 4-5 zmiennymi, które później posłużą nam za dane do rozmytej logiki.
oczywiście generator randomowy.
zmienne: temperatura, nasłonecznienie, wilgotność powietrza, wilgotność gleby, opady
każda zmienna w zakresie 0-4

**Comment by czeskij** [comment]
ee, gdzie będzie rozmycie?
myślałem że na podstawie fikcyjnych, ale prawdopodobnych wartości (od -20 do 40 dla temperatury, procenty dla wilgotności etc.) dopiero będzie determinowany stopień (np. bardzo zimno, zimno, ciepło, bardzo ciepło, gorąco; albo tak jak mowisz, od 0-4).

**Comment by yyarp** [comment]
ustalam takie wartości zmiennych do rozmyć późniejszych:

wilgotność gleby - centybary 0-200
nasłonecznienie - jednostkowe(W/m^2 100-800), czasowe(Wh/m^2 suma średnich nasłonecznień w czasie)
wilgotność powietrza - względna procentowo
temperatura - st. celsjusza -20 do 40
opady - 0-1000 mm/m^2

**Comment by yyarp** [comment]
zrobione
