### ISSUE TITLE
rozmycie wartości

### ISSUE THREAD

**Issue by yyarp** [yyarp/WeedMoister#2]
trzeba napisać rozmycie wartości z generatora, najlepiej jako osobną klasę dziedziczącą po generatorze. żeby tabelę spokojnie przekazać do rozmycia ;p
wszystkie wartości najlepiej w pięciu stanach typu:
none, low, medium, high, fuckload(?) :D

**Comment by yyarp** [comment]
rozmycie
opady: 
	0-200 bardzo małe 0
	201-400 małe 1
	401-600 średnie 2
	601-800 średnio duże 3
	801-1000 duże 4
gleba:
	0-40 bardzo mała 0
	41-80 mała 1
	81-120 średnia 2
	121-160 średnio duża 3
	161-200 duża 4
powietrze:
	0-10 bardzo mała 0
	11-20 mała 1
	21-40 średnia 2 
	41-60 średnio duża 3
	61-100 duża 4
słońce:
	100-200 bardo małe 0
	201-300 małe 1
	301-500 średnie 2
	501-650 średnio duże 3
	651-800 duże 4
temperatura:
	-20-0 bardzo niska 0
	1-10 niska 1
	11-20 średnia 2 
	21-30 wysoka 3
	31-40 bardzo wysoka 4

**Comment by czeskij** [comment]
>średnio duże słońce

zatwierdzam tak czy inaczej :D

**Comment by yyarp** [comment]
no nasłonecznienie

**Comment by czeskij** [comment]
i know, i know ; p

**Comment by yyarp** [comment]
potrzebne poprawienie rozmycia, zaraz się tym zajmę. jakieś uwagi?

**Comment by yyarp** [comment]
pojedyncza metoda rozmycia wartości jednej będzie mniej więcej się przedstawiała tak: 
(tam gdzie nie ma w ifach, tam będzie analogicznie)
protected double[] FuzzyPrecipitation() 
        {
            double[] fuzzyValuesPrec = new double[5];
            if (temp_table[0] <= 200) {
                if(temp_table[0] <= 150) {
                    fuzzyValuesPrec[0] = 1.00; //very low
                    fuzzyValuesPrec[1] = 0.00; //low
                    fuzzyValuesPrec[2] = 0.00; //medium
                    fuzzyValuesPrec[3] = 0.00; //medium high
                    fuzzyValuesPrec[4] = 0.00; //high
                }
                else if (temp_table[0] > 150 && temp_table[0] <= 200) {
                    fuzzyValuesPrec[0] = 1.00;
                    fuzzyValuesPrec[1] = (200 - temp_table[0])/(50);
                    fuzzyValuesPrec[2] = 0.00;
                    fuzzyValuesPrec[3] = 0.00;
                    fuzzyValuesPrec[4] = 0.00;
                }
            } else if (temp_table[0] > 150 && temp_table[0] <= 400) {

            } else if (temp_table[0] > 300 && temp_table[0] <= 600) {
                
            } else if (temp_table[0] > 550 && temp_table[0] <= 800) {
                
            } else if (temp_table[0] > 770 && temp_table[0] <= 1000) {
                
            } else {
                
            }
            for (int i = 0; i < 5; ++i)
            {
                Console.Write(fuzzyValuesPrec[i] + " ");
            }
                return fuzzyValuesPrec;
        }

**Comment by yyarp** [comment]
done
