### ISSUE TITLE
ograniczenie ilości zmiennych

### ISSUE THREAD

**Issue by czeskij** [yyarp/WeedMoister#6]
na podstawie [tego](http://aslowik.republika.pl/Fuzzy_Logic_III.pdf) wywnioskowałem, że możemy mieć problem z ogarnięciem bazy reguł dla naszego systemu.
or am I wrong?

**Comment by yyarp** [comment]
niekoniecznie, można zawsze wziąć dwie zmienne i wywnioskować jedną, potem tą zmienną wywnioskowaną i wziąć następną i wniosek, itd. aż do końca zmiennych. pięciokrotne wnioskowanie, bym to nazwał.

**Comment by czeskij** [comment]
a, w tym sensie. ale to musimy mieć w takim razie jakąś hierarchię ważności?

**Comment by yyarp** [comment]
a nie można po kolei? tak jak w tavblicy siedzą?

**Comment by czeskij** [comment]
w sumie, chyba wyjdzie na jedno. to spoko, zobaczymy tylko co p. Słowik na to powie, można go w sumie zapytać na konsultacjach jutro
